name: scrape-da-an

on:
  schedule:
    - cron: "*/1 * * * *"   # 每 5 分鐘
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: scrape-da-an
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python scrape_da_an.py --csv data/all_people.csv
          
      - name: Upload debug snapshot (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-html
          path: |
            data/last_page.html
            data/last_page.png
          if-no-files-found: ignore

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add data/all_people.csv
            git commit -m "Update data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes"
          fi
